### ISSUE TITLE
Endless error loop with function parse_logs

### ISSUE THREAD

**Issue by jlboura** [lunyiliu/LogPrompt#2]
Hello

I run the LogPrompt_code.py script on a sample .xls with 3 lines, with CoT strategy. The command line is the following:

python3 LogPrompt_code.py --API_KEY <My ChatGPT Key> --dataset example.xls --strategy CoT --output_file_name testCOT

The output is a endless display of "error! choice" :

![image](https://github.com/user-attachments/assets/e61b13ab-7507-4b14-ad74-9767ec1cb09c)

I say "endless" because it last until I do Ctrl-C.

I added some prints in the code to debug, and it appears that the error, whatever its cause, appear in the function parse_logs. 
More precisely, in the "while parsed_log =='':" loop: res variable appears to be adequatly instancied, the error is probably that the Exception is then triggered for unknown reason. I also don't figure out why the endless loop whereas the sample file is only 3 lines long.

Your tool is very interesting, I can't wait to continue explore it once this issue is solved :)

Best regards

**Comment by soumya-ghosh-sndk** [comment]
I am also facing the same issue.Can a hot fix of the same be provided for me to continue.

**Comment by soumya-ghosh-sndk** [comment]
Request to kindly fix the issue.

**Comment by lunyiliu** [comment]
Please refer to #3
